Document: munkres
Title: Debian munkres Manual
Author: <insert document author here>
Abstract: This manual describes what munkres is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/munkres/munkres.sgml.gz

Format: postscript
Files: /usr/share/doc/munkres/munkres.ps.gz

Format: text
Files: /usr/share/doc/munkres/munkres.text.gz

Format: HTML
Index: /usr/share/doc/munkres/html/index.html
Files: /usr/share/doc/munkres/html/*.html


